### ISSUE TITLE
bug: update 方法会新增一条记录

### ISSUE THREAD

**Issue by ltaoo** [vikadata/vika.js#1]
`datasheet.update` 方法

看网站 `curl` 示例是发了 `PATCH` 请求，代码这里是 `POST` 请求。我本地修改成 `PATCH` 后打包是能正常更新的。

https://github.com/vikadata/vika.js/blob/master/lib/request.ts#L160

**Comment by JailBreakC** [comment]
感谢反馈，已修复，请更新版本至 0.1.7

Fixed in 0.1.7

commit: https://github.com/vikadata/vika.js/commit/84e6ce48eb4238d715685f0392788f7d65be15f0
